apiVersion: v1
kind: Namespace
metadata:
  name: liars-system
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: engine-config
  namespace: liars-system
data:
  bank_network: "http://geth-service.liars-system.svc.cluster.local:8545"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: engine
  namespace: liars-system
spec:
  selector:
    matchLabels:
      app: engine
  template:
    metadata:
      labels:
        app: engine
    spec:
      terminationGracePeriodSeconds: 60
      # CONFIGURATION FOR THE ENGINE AND UI
      containers:
      # game-engine container configuration
      - name: game-engine
        image: game-engine-image
        ports:
        - name: game-engine
          containerPort: 3000
        - name: ge-debug
          containerPort: 4000
        readinessProbe: # readiness probes mark the service available to accept traffic.
          httpGet:
            path: /debug/readiness
            port: 4000
          initialDelaySeconds: 2
          periodSeconds: 15
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 2
        livenessProbe: # liveness probes mark the service alive or dead (to be restarted).
          httpGet:
            path: /debug/liveness
            port: 4000
          initialDelaySeconds: 2
          periodSeconds: 30
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 2
        env:
        - name: GAME_CONTRACT_ID
          valueFrom:
            secretKeyRef:
              name: contract-id
              key: id
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: KUBERNETES_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: KUBERNETES_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: KUBERNETES_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
---
apiVersion: v1
kind: Service
metadata:
  name: engine-service
  namespace: liars-system
