apiVersion: v1
kind: Namespace
metadata:
  name: liars-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: engine
  namespace: liars-system
spec:
  selector:
    matchLabels:
      app: engine
  template:
    metadata:
      labels:
        app: engine
    spec:
      terminationGracePeriodSeconds: 60
      initContainers:
      # NEED TO DEPLOY CONTRACT AND GET CONTRACTID SET AS
      # CONFIGURATION FOR THE ENGINE AND UI
      containers:
      # game-engine container configuration
      - name: game-engine
        image: game-engine-image
        ports:
        - name: game-engine
          containerPort: 3000
        - name: game-engine-debug
          containerPort: 4000
        readinessProbe: # readiness probes mark the service available to accept traffic.
          httpGet:
            path: /debug/readiness
            port: 4000
          initialDelaySeconds: 2
          periodSeconds: 15
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 2
        livenessProbe: # liveness probes mark the service alive or dead (to be restarted).
          httpGet:
            path: /debug/liveness
            port: 4000
          initialDelaySeconds: 2
          periodSeconds: 30
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 2
        env:
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: KUBERNETES_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: KUBERNETES_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: KUBERNETES_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
---
apiVersion: v1
kind: Service
metadata:
  name: engine-service
  namespace: liars-system
