apiVersion: v1
kind: Namespace
metadata:
  name: liars-system
---
# We need the vault credentials to exist across pod restarts
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: liars-system
  name: vault-credentials
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: engine
  namespace: liars-system
spec:
  selector:
    matchLabels:
      app: engine
  template:
    metadata:
      labels:
        app: engine
    spec:
      terminationGracePeriodSeconds: 60
      volumes:
        - name: vault
          persistentVolumeClaim:
            claimName: vault-credentials
      initContainers:
      - name: init-vault-server
        image: game-engine-image
        command: ['./admin', '-v']
        volumeMounts:
          - name: vault
            mountPath: /vault
      - name: init-vault-keys
        image: game-engine-image
        command: ['./admin', '-y']
      containers:
      - name: game-engine
        image: game-engine-image
        ports:
        - name: game-engine
          containerPort: 3000
        - name: ge-debug
          containerPort: 4000
        readinessProbe:
          httpGet:
            path: /debug/readiness
            port: 4000
          initialDelaySeconds: 2
          periodSeconds: 15
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 2
        livenessProbe:
          httpGet:
            path: /debug/liveness
            port: 4000
          initialDelaySeconds: 2
          periodSeconds: 30
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 2
        env:
        - name: GAME_CONTRACT_ID
          valueFrom:
            secretKeyRef:
              name: contract-id
              key: id
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: KUBERNETES_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: KUBERNETES_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: KUBERNETES_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
---
apiVersion: v1
kind: Service
metadata:
  name: engine-service
  namespace: liars-system
