apiVersion: v1
kind: Namespace
metadata:
  name: liars-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: engine
  namespace: liars-system

spec:
  selector:
    matchLabels:
      app: engine

  template:
    metadata:
      labels:
        app: engine

    spec:
      terminationGracePeriodSeconds: 60

      initContainers:
      - name: init-ge-migrate
        image: engine-image
        command: ['./admin', 'migrate']

      containers:
      - name: game-engine
        image: engine-image

        ports:
        - name: game-engine
          containerPort: 3000
        - name: game-engine-dbg
          containerPort: 4000

        readinessProbe:
          httpGet:
            path: /v1/readiness
            port: 3000
          initialDelaySeconds: 2
          periodSeconds: 15
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 2

        livenessProbe:
          httpGet:
            path: /v1/liveness
            port: 3000
          initialDelaySeconds: 2
          periodSeconds: 30
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 2

        env:
        - name: GAME_CONTRACT_ID
          valueFrom:
            secretKeyRef:
              name: contract-id
              key: id
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: KUBERNETES_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: KUBERNETES_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: KUBERNETES_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName

---

apiVersion: v1
kind: Service
metadata:
  name: engine-service
  namespace: liars-system
