FROM node:16 as build

# create destination directory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

# Set environment variables
# COPY ../../app/services/game/.env.kind /usr/src/app/.env

# copy the app, note .dockerignore
COPY ../../app/services/game/package.json /usr/src/app/package.json
RUN npm install
COPY ../../app/services/game/. /usr/src/app/
RUN npm run generate

### STAGE 2: CADDY ###
FROM caddy:2.6-alpine
COPY --from=build /usr/src/app/dist /usr/share/caddy/
EXPOSE 80