apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/engine/
patches:
  - path: ./dev-engine-patch.yaml
images:
  - name: engine-image
    newName: ardanlabs/liars/engine
    newTag: 0.0.1
