apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/engine/
patches:
  - path: ./dev-engine-patch.yaml
images:
  - name: game-engine-image
    newName: liarsdice-game-engine
    newTag: "1.0"
