apiVersion: v1
kind: Namespace
metadata:
  name: liars-system
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: "geth-keystore"
  namespace: liars-system
stringData:
  UTC--2022-05-12T14-47-50.112225000Z--6327a38415c53ffb36c11db55ea74cc9cb4976fd: |
    {"address":"6327a38415c53ffb36c11db55ea74cc9cb4976fd","crypto":{"cipher":"aes-128-ctr","ciphertext":"f321f79339bfe67b7639c601fb764e8c1cadf18f8230aa2bfb2a468930c0e25a","cipherparams":{"iv":"b3b899daf5353eb9bba8472af607dd1d"},"kdf":"scrypt","kdfparams":{"dklen":32,"n":262144,"p":1,"r":8,"salt":"2dd98eb820aa1e00856e9f1fdbdb18c44525c10b81ca7ddc1c80efc25bf3be76"},"mac":"119bfd0bedd9120903c09af73cb3d34c2b0b153dbd6300ca00df3504ca0409bb"},"id":"ce7ff8ab-7455-4eaf-bae9-7d338f8d0d5c","version":3}
  UTC--2022-05-13T16-57-20.203544000Z--8e113078adf6888b7ba84967f299f29aece24c55: |
    {"address":"8e113078adf6888b7ba84967f299f29aece24c55","crypto":{"cipher":"aes-128-ctr","ciphertext":"2e25d38eaed901e62ca9093c6f3e65a0d958359676af76f6eddfcad9c55abcac","cipherparams":{"iv":"a94f7a80b38d4202ccef793a532c2c26"},"kdf":"scrypt","kdfparams":{"dklen":32,"n":4096,"p":6,"r":8,"salt":"f3933d628296dbbbb9acf23282c7477378dd9b7833d7c690ed98f300c102c368"},"mac":"83138be2e3465ae0d378ea2405933cf695d71e8ce7c220446a4ccaf8f3ea5019"},"id":"6d373459-c586-46e5-9913-b79c2e6400fa","version":3}
  UTC--2022-05-13T16-59-42.277071000Z--0070742ff6003c3e809e78d524f0fe5dcc5ba7f7: |
    {"address":"0070742ff6003c3e809e78d524f0fe5dcc5ba7f7","crypto":{"cipher":"aes-128-ctr","ciphertext":"eddd1119b05ac505c509e2ead3f7e85f8c0dc64752f10bd26d13e5a5af51012e","cipherparams":{"iv":"f087fbe3753443e43245228694a83514"},"kdf":"scrypt","kdfparams":{"dklen":32,"n":4096,"p":6,"r":8,"salt":"ffbc851267301d39079d2567fc6adea1e711c09f0fd877c42a0fcafd32ef7c49"},"mac":"b71814dd465f80ecd336e03d0804338c22dfad77375ddb393b1c357d7fe22a40"},"id":"29299d47-11c6-4a29-8603-579b7368e997","version":3}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: "geth-password"
  namespace: liars-system
stringData:
  password: "123"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: geth
  namespace: liars-system
spec:
  selector:
    matchLabels:
      app: geth
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: geth
    spec:
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      terminationGracePeriodSeconds: 60
      initContainers:
        - name: copy-keystore
          image: busybox
          command: ["sh", "-c", "mkdir -p /ethereum/keystore; cp /secrets/keystore/* /ethereum/keystore"]
          volumeMounts:
            - name: vol-ethereum
              mountPath: /ethereum
            - name: geth-keystore
              mountPath: /secrets/keystore
      containers:
        - name: geth
          image: geth-image
          args:
            - --dev
            - --http
            - --http.addr=0.0.0.0
            - --http.corsdomain=*
            - --http.vhosts=*
            - --allow-insecure-unlock
            - --rpc.allow-unprotected-txs
            - --mine
            - --miner.threads=1
            - --verbosity=5
            - --datadir=/ethereum
            - --unlock=0x6327A38415C53FFb36c11db55Ea74cc9cB4976Fd
            - --password=/secrets/password
          ports:
            - name: geth
              containerPort: 8545
            - name: geth-p2p
              containerPort: 30303
          volumeMounts:
            - name: vol-ethereum
              mountPath: /ethereum
            - name: geth-password
              mountPath: /secrets
              readOnly: true
      volumes:
        - name: vol-ethereum
          hostPath:
            path: /ethereum  # matches kind containerPath:
        - name: geth-password
          secret:
            secretName: "geth-password"
        - name: geth-keystore
          secret:
            secretName: "geth-keystore"

---
apiVersion: v1
kind: Service
metadata:
  name: geth-service
  namespace: liars-system
spec:
  type: ClusterIP
  selector:
    app: geth
  ports:
    - name: geth
      port: 8545
      targetPort: geth
    - name: geth-p2p
      port: 30303
      targetPort: geth-p2p
