apiVersion: v1
kind: Namespace
metadata:
  name: liars-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: geth
  namespace: liars-system
spec:
  selector:
    matchLabels:
      app: geth
  template:
    metadata:
      labels:
        app: geth
    spec:
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      terminationGracePeriodSeconds: 60
      containers:
        - name: geth
          image: geth-image
          args:
            - --dev
            - --ipcpath=/ethereum/geth.ipc
            - --http
            - --http.addr=0.0.0.0
            - --http.corsdomain=*
            - --http.vhosts=*
            - --allow-insecure-unlock
            - --rpc.allow-unprotected-txs
            - --mine
            - --miner.threads=1
            - --verbosity=5
            - --datadir=/ethereum
            - --unlock=0x6327A38415C53FFb36c11db55Ea74cc9cB4976Fd
            - --password=/ethereum/password
          ports:
            - name: geth
              containerPort: 8545
            - name: geth-p2p
              containerPort: 30303
          volumeMounts:
            - name: vol-ethereum
              mountPath: /ethereum
      volumes:
        - name: vol-ethereum
          hostPath:
            path: /ethereum  # matches kind containerPath:
---
apiVersion: v1
kind: Service
metadata:
  name: geth-service
  namespace: liars-system
spec:
  type: ClusterIP
  selector:
    app: geth
  ports:
    - name: geth
      port: 8545
      targetPort: geth
    - name: geth-p2p
      port: 30303
      targetPort: geth-p2p
