apiVersion: v1
kind: Namespace
metadata:
  name: liars-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui
  namespace: liars-system
spec:
  selector:
    matchLabels:
      app: ui
  template:
    metadata:
      labels:
        app: ui
    spec:
      terminationGracePeriodSeconds: 60
      volumes:
        - name: vault
          persistentVolumeClaim:
            claimName: vault-credentials
      initContainers:
      # game-engine init container configuration
      - name: init-vault-server
        image: game-engine-image
        command: ['./admin', '-v']
        volumeMounts:
          - name: vault
            mountPath: /vault
      containers:
      # game-engine container configuration
      - name: game-ui
        image: game-ui-image
        ports:
        - name: game-ui
          containerPort: 80
          hostPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: ui-service
  namespace: liars-system
