apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/ui/
patchesStrategicMerge:
  - ./dev-ui-patch.yaml
images:
  - name: game-ui-image
    newName: liarsdice-game-ui
    newTag: "1.0"
  - name: game-engine-image
    newName: liarsdice-game-engine
    newTag: "1.0"
