name: Go

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.25.0

      # - name: Staticheck
      #   run: |
      #     wget -O staticcheck.tgz https://github.com/dominikh/go-tools/releases/download/2022.1/staticcheck_linux_amd64.tar.gz
      #     sudo tar -xzf staticcheck.tgz
      #     ./staticcheck/staticcheck --version
      #     ./staticcheck/staticcheck -checks=all ./...

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v business/core/game/game_test.go
