name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.21.6

    - name: Staticheck
      run: |
        go install honnef.co/go/tools/cmd/staticcheck@latest
        staticcheck/staticcheck -checks=all ./...

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v business/core/game/game_test.go
